site_name: Cobra
repo_url: https://github.com/wufeifei/cobra
site_description: Cobra is a static code security analyzed system
site_author: Feei
site_favicon: favicon.ico
copyright: Copyright (c) 2017 Feei. All rights reserved
theme: readthedocs
pages:
- Home: 'index.md'
- Getting Started:
  - Introduction: 'introduction.md'
  - Installation: 'installation.md'
  - Configuration: 'configuration.md'
- Usage:
  - GUI: 'GUI.md'
  - CLI: 'CLI.md'
  - API: 'API.md'
- Structure:
  - Architecture: 'architecture.md'
  - Tables: 'tables.md'
- Resources:
  - Rule List: 'rule_list.md'
  - Vulnerabilities: 'vulnerabilities.md'
  - Languages: 'languages.md'
- Modules:
  - Rule: 'rule.md'
  - Detection URI: 'detection_uri.md'
  - Scheduler: 'scheduler.md'
- FAQ:
  - FAQ: 'FAQ.md'
  - Exception: 'exception.md'
- Reference:
  - Rule Source: 'rule_source.md'
  - Third Party: 'THIRD-PARTY.md'